version: '3.5'

services:

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    ports:
      - ${NGINX_PORT}:80

  api:
    build: ./api
    restart: unless-stopped
    command: api
    env_file:
      - .env
      - api/api.env
    volumes:
      - ./files:${DOCUMENTS_PATH}
      - ./logs:${LOGS_PATH}
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./mongo_data:/data/db